name: EducAI_ENV
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - attrs=25.1.0
  - beautifulsoup4=4.13.3
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - defusedxml=0.7.1
  - expat=2.6.4
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - jinja2=3.1.5
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_pygments=0.3.0
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libdeflate=1.23
  - libedit=3.1.20230828
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libjpeg-turbo=3.0.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.45.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - mistune=3.1.2
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - openssl=3.4.1
  - packaging=24.2
  - pandoc=3.6.3
  - pandocfilters=1.5.0
  - pip=25.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pygments=2.19.1
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python_abi=3.12
  - pyzmq=26.2.1
  - readline=8.2
  - referencing=0.36.2
  - rpds-py=0.23.1
  - setuptools=75.8.0
  - six=1.17.0
  - soupsieve=2.5
  - sqlite=3.45.2
  - tinycss2=1.4.0
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - webencodings=0.5.1
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - certifi==2025.1.31
      - click==8.1.8
      - dnspython==2.7.0
      - email-validator==2.2.0
      - fastapi==0.115.8
      - fastapi-cli==0.0.7
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - idna==3.10
      - itsdangerous==2.2.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - orjson==3.10.15
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-extra-types==2.10.2
      - pydantic-settings==2.8.0
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - rich==13.9.4
      - rich-toolkit==0.13.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.38
      - starlette==0.45.3
      - typer==0.15.1
      - ujson==5.10.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - watchfiles==1.0.4
      - websockets==15.0
prefix: /home/sulayman/miniconda3/envs/EducAI_ENV
